#version 430 core

layout (local_size_x = 8, local_size_y = 8) in;

layout (rg32f, binding = 0) uniform readonly image2D uSource;
layout (rg32f, binding = 1) uniform writeonly image2D uDestination;

uniform int uResolution;
uniform float uScale;

void main()
{
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= uResolution || coord.y >= uResolution) {
        return;
    }

    vec2 value = imageLoad(uSource, coord).xy * uScale;
    imageStore(uDestination, coord, vec4(value, 0.0, 1.0));
}
